import json
import pytest
import imageio
import pathlib

from dragonfly_automation.tests.mocks import mm2python_mocks
from dragonfly_automation.fov_models import PipelineFOVScorer


@pytest.fixture(scope='session')
def project_dirpath():
    return pathlib.Path(__file__).parent.parent


@pytest.fixture(scope='session')
def artifacts_dirpath(project_dirpath):
    return project_dirpath / 'dragonfly_automation' / 'tests' / 'artifacts'


@pytest.fixture(scope='session')
def raw_hcs_position_list(artifacts_dirpath):
    '''
    A real raw position list generated by the HCS site generator (on Micromanager beta)
    for a full 96-well plate with 36 sites in each well
    '''
    filename = 'raw-hcs-position-list-with-96-wells-36-sites.pos'
    with open(artifacts_dirpath / filename, 'r') as file:
        return json.load(file)


@pytest.fixture(scope='session')
def snaps_dirpath(artifacts_dirpath):
    return artifacts_dirpath / 'snaps'


@pytest.fixture(scope='session')
def fov_snap_and_score(snaps_dirpath):
    snap = imageio.imread(snaps_dirpath / 'good-1.tif')
    expected_score = 0.85
    return snap, expected_score


@pytest.fixture(scope='session')
def fov_snaps_high_score(snaps_dirpath):
    return [
        imageio.imread(snaps_dirpath / 'good-1.tif'),
        imageio.imread(snaps_dirpath / 'good-2.tif'),
        imageio.imread(snaps_dirpath / 'good-3.tif'),
    ]


@pytest.fixture(scope='session')
def fov_snaps_low_score(snaps_dirpath):
    snaps = []
    for kind in ['clumpy', 'overconfluent', 'sparse']:
        snaps.extend(
            [
                imageio.imread(snaps_dirpath / f'{kind}-1.tif'),
                imageio.imread(snaps_dirpath / f'{kind}-2.tif'),
                imageio.imread(snaps_dirpath / f'{kind}-3.tif'),
            ]
        )
    return snaps


@pytest.fixture(scope='session')
def fov_snaps_too_few(snaps_dirpath):
    return [
        imageio.imread(snaps_dirpath / 'too-few-1.tif'),
        imageio.imread(snaps_dirpath / 'too-few-2.tif'),
        imageio.imread(snaps_dirpath / 'too-few-3.tif'),
    ]


@pytest.fixture(scope='session')
def fov_snap_no_nuclei(snaps_dirpath):
    return imageio.imread(snaps_dirpath / 'no-nuclei-1.tif')


@pytest.fixture(scope='session')
def trained_fov_scorer(project_dirpath):

    fov_model_dir = str(project_dirpath / 'models' / '2019-10-08')
    fov_scorer = PipelineFOVScorer(save_dir=fov_model_dir, mode='prediction', random_state=42)
    fov_scorer.load()
    fov_scorer.train()
    fov_scorer.validate()
    return fov_scorer


@pytest.fixture(scope='function')
def event_logger():
    class EventLogger:
        def __init__(self):
            self.events = []

        def __call__(self, event):
            self.events.append(event)

    return EventLogger()


@pytest.fixture(scope='session')
def get_mocked_interface():
    '''
    A factory fixture to make it easy to switch between using mm2python and pycromanager mocks
    '''
    return mm2python_mocks.get_mocked_interface
