import os
import sys
import skimage
import numpy as np


def interpolate_stage_positions(positions_filepath):
    '''
    This method refactors the 'StageTiltDragonfly.py' script

    '''

    pass




def rename_tiff_stacks(positions_filepath, tiff_dirpath, logger=None):
    '''
    Rename TIFF stacks acquired by a scripted acquisition that 
    1) used stage positions generated by the 96-well-plate stage position plugin for MicroManager
    2) saved TIFF stacks using a datastore object returned by `createMultipageTIFFDatastore`

    In other words, this method refactors and generalizes Nathan's 'FileRename_HalfPlates_MM2.py' script.


    ASSUMPTIONS
    -----------


    PARAMETERS
    ----------



    '''

    pass